### ISSUE TITLE
Can't login using the executable file. 

### ISSUE THREAD

**Issue by ghost** [davidegironi/dentned#1]
Hello!

Thanks for this wonderful application. I managed to install the SQL server and restore the database, but when I start the executable file I get a connection error. I am completely lost as I don't know exactly what to modify to connect properly. 

Could you please assist? Thank you!

**Comment by davidegironi** [comment]
Hello, you have to set the ConnectionString in the config file.
The format should be something like the string below, of couse you have to replace DATASOURCE, INITIALCATALOG, USERID, PASSWORD with the parameters you set.
```
<add name="dentnedEntities" connectionString="metadata=res://*/Entity.Model_dentned.csdl|res://*/Entity.Model_dentned.ssdl|res://*/Entity.Model_dentned.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DATASOURCE;initial catalog=INITIALCATALOG;user id=USERID;password=PASSWORD;MultipleActiveResultSets=True;App=EntityFramework&quot;"  />
```
