### ISSUE TITLE
Unable to login/signup

### ISSUE THREAD

**Issue by RiPPERD** [davidegironi/dentned#2]
Hello i came across this yesterday i have installed it fine but its asking me to login but there is no login or signup option or default details... can you please provide

**Comment by davidegironi** [comment]
Hello, do you mean the password protected forms feature? If so, just leave the "passwordProtectedForms" settings empty in config file.

**Comment by RiPPERD** [comment]
Hello thank you for your reply, 
So im using the web version hosted on my own server, once i play around with the php files for the database (which it still hasn't added any data to it) it loads the page tells me i must login and i have a login username and password box at top of screen... only trouble is i have not installed or setup a username as there was no option for this... im assuming i have missed something but i cannot work out what it is
i can send you a link to server if i can PM on here and i will post error log to here

**Comment by RiPPERD** [comment]
this is the screen im talking about
[url=https://ibb.co/fxZYTTC][img]https://i.ibb.co/wz8N22K/Untitled.png[/img][/url]

this is the error log after trying username 'admin' password 'admin'

[20-Aug-2019 23:16:31 Europe/Rome] PHP Notice:  Undefined variable: result in /home/decis7gc/public_html/websites/Dentist/mssqlwrapper.php on line 52
[20-Aug-2019 23:16:31 Europe/Rome] PHP Notice:  Undefined variable: result in /home/decis7gc/public_html/websites/Dentist/mssqlwrapper.php on line 52

Here is my wrapper.php file minus any secure data

<?php
// Copyright (c) 2015 Davide Gironi
//
// Please refer to LICENSE file for licensing information.

defined( '_VALID_' ) or die( 'Restricted access' );

//MSSQL connection handler class
class MSSQLWrapper {
  protected $connection = null;
  protected $driver = 'mssqli';
  
  //MSSQL wrapper constructor
  public function __construct($driver, $hostname, $database, $username, $password) {
    $this->driver = $driver;
    if(!$this->connect($hostname, $database, $username, $password))
      die("Couldn't connect to SQL Server."); 
  }
  
  //Open a connection
  public function connect($hostname, $database, $username, $password) {
    if($this->driver == 'sqlsrv') {
      $this->connection = sqlsrv_connect($hostname, array( "dentist"=>$database, "dentist"=>$username, "dentist"=>$password));
      if(!$this->connection)
        return false;
    } else if($this->driver == 'mssql') {
      $this->connection = mssql_pconnect($hostname, $username, $password);
      if(!$this->connection)
        return false;
      if(!mssql_select_db($database, $this->connection))
        return false; 
    }
    return true;
  }
  
  //Close a connection
  public function close() {
    if($this->driver == 'sqlsrv') {
      sqlsrv_close($this->connection);
    } else if($this->driver == 'mssql') {
      mssql_close($this->connection);
    }
  }
  
  //Perform a query
  public function query($query) {
    if($this->driver == 'sqlsrv') {
      $result = sqlsrv_query($this->connection, $query);
    } else if($this->driver == 'mssql') {
      $result = mssql_query($query, $this->connection);
    }
    return $result;
  }
  
  //Fetch some data
  public function fetchData($query) {
    $data_array = array();
    $result = $this->query($query);
    if($this->driver == 'sqlsrv') {
      while ($row = sqlsrv_fetch_array($result)) {
        $data_array[] = $row;                          
      }
    } else if($this->driver == 'mssql') {
      while ($row = mssql_fetch_array($result)) {
        $data_array[] = $row;                          
      }
    }    
    return $data_array;           
  }
  
  //MSSQL escape characters
  public function escape($data) {
    if(is_numeric($data))
      return $data;
    $unpacked = unpack('H*hex', $data);
    return '0x' . $unpacked['hex'];
  }

}

**Comment by RiPPERD** [comment]
this is the screen im talking about
<a href="https://ibb.co/fxZYTTC"><img src="https://i.ibb.co/wz8N22K/Untitled.png" alt="Untitled" border="0"></a>

this is the error log after trying username 'admin' password 'admin'

[20-Aug-2019 23:16:31 Europe/Rome] PHP Notice:  Undefined variable: result in /home/decis7gc/public_html/websites/Dentist/mssqlwrapper.php on line 52
[20-Aug-2019 23:16:31 Europe/Rome] PHP Notice:  Undefined variable: result in /home/decis7gc/public_html/websites/Dentist/mssqlwrapper.php on line 52

Here is my wrapper.php file minus any secure data

<?php
// Copyright (c) 2015 Davide Gironi
//
// Please refer to LICENSE file for licensing information.

defined( '_VALID_' ) or die( 'Restricted access' );

//MSSQL connection handler class
class MSSQLWrapper {
  protected $connection = null;
  protected $driver = 'mssqli';
  
  //MSSQL wrapper constructor
  public function __construct($driver, $hostname, $database, $username, $password) {
    $this->driver = $driver;
    if(!$this->connect($hostname, $database, $username, $password))
      die("Couldn't connect to SQL Server."); 
  }
  
  //Open a connection
  public function connect($hostname, $database, $username, $password) {
    if($this->driver == 'sqlsrv') {
      $this->connection = sqlsrv_connect($hostname, array( "dentist"=>$database, "dentist"=>$username, "dentist"=>$password));
      if(!$this->connection)
        return false;
    } else if($this->driver == 'mssql') {
      $this->connection = mssql_pconnect($hostname, $username, $password);
      if(!$this->connection)
        return false;
      if(!mssql_select_db($database, $this->connection))
        return false; 
    }
    return true;
  }
  
  //Close a connection
  public function close() {
    if($this->driver == 'sqlsrv') {
      sqlsrv_close($this->connection);
    } else if($this->driver == 'mssql') {
      mssql_close($this->connection);
    }
  }
  
  //Perform a query
  public function query($query) {
    if($this->driver == 'sqlsrv') {
      $result = sqlsrv_query($this->connection, $query);
    } else if($this->driver == 'mssql') {
      $result = mssql_query($query, $this->connection);
    }
    return $result;
  }
  
  //Fetch some data
  public function fetchData($query) {
    $data_array = array();
    $result = $this->query($query);
    if($this->driver == 'sqlsrv') {
      while ($row = sqlsrv_fetch_array($result)) {
        $data_array[] = $row;                          
      }
    } else if($this->driver == 'mssql') {
      while ($row = mssql_fetch_array($result)) {
        $data_array[] = $row;                          
      }
    }    
    return $data_array;           
  }
  
  //MSSQL escape characters
  public function escape($data) {
    if(is_numeric($data))
      return $data;
    $unpacked = unpack('H*hex', $data);
    return '0x' . $unpacked['hex'];
  }

}

**Comment by davidegironi** [comment]
you have to set values for your connection in the config.inc.php file.
Consider that this web page is just for the planner, it does nothing than viewing appointment. In order to set username and password for this interface you have to use the main desktop application.

**Comment by RiPPERD** [comment]
i have setup config file i changed to mssqli though as my server doesnt support mssql (should be fine)

so do i have to use both server and desktop versions to get this to work? thank you for your speedy replies... sorry for my delayed replies lol

**Comment by davidegironi** [comment]
yes, as specified in features the web is just a "Calendar web interface". To setup password for the calendar view you have to use the desktop application.
