### ISSUE TITLE
How to install using xammp

### ISSUE THREAD

**Issue by hodgson3000** [davidegironi/dentned#6]
Hi Guys

I'm new on this project, I´d like to install that on xammp

could u plz provide me a manual or give me some tips for doing that?

tks in advance

**Comment by davidegironi** [comment]
Dear @hodgson3000 , unluckily I do not have any xampp docs or howto. Please note that the web page only covers the agenda functionalities. To run it on a xampp, you just have to setup PHP and the SQL server PHP module, also you have to edit the config php file.
