### ISSUE TITLE
How to install DentneD on a Windows machine

### ISSUE THREAD

**Issue by romanobarassi** [davidegironi/dentned#7]
**1.** Download DentneD
**2.** Download **Microsoft SQL Express 2019**
**3.** Install Microsoft SQL Express 2019: during install process select the mixed auth mode and choose the super admin password (sa)
**4.** Download and install **Azure Data Studio**
**5.** Open Azure Data Studio, create a new connection with “localhost” hostname, “sa” user and “PassChoosedInPoint3” password.
**6.** In Azure Data Studio double click on created connection (or right-click --> Manage) and select _Restore_. Select the “dentned.bak” file (in “_DBDump” folder).
**7.** Open “DentneD.exe.config” config file with a text editor and insert all needed parameters in the database connection row: server, database name, user, password. Select the language (“en” or “it”) a few lines below.
**8.** Download and copy the **ATL100.DLL library** in the backup folder or download "Visual C++ 2010 Redistributable x86" package.
**9.** Open “config.db-backup” config file with a text editor and edit it as you prefer:
Ex.
_set SQLFOLDER=C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup
set DESTPATH=C:\Dentned-backup_
**10.** Create a **cronjob** from Windows Administrative Tools for the automatic backup. Choose the db-backup.bat file in the backup folder.
**11.** Start DentneD and check its correct functioning

**Comment by davidegironi** [comment]
Thank your @romanobarassi for this guide. I've added this as a link in the README file.

**Comment by luism566** [comment]
Hello! I try to identify the file "DentneD.exe.config" but I can't find it in the repository, is it the correct name or does it refer to another .config?.

thank

**Comment by davidegironi** [comment]
Hello, you will find it in the binary relase. It's basically tha App.config renamed and prepared by VS compiler.

**Comment by luism566** [comment]
Thank you Davide!

I make a query and I hope not to bother you more, I apologize for the inconvenience and thank you for your help.

I try to compile the project in visual studio after installing the Microsoft Windows with .NET framework 4.6.2 development module and I am not an expert at all and I get the error that I attach in the image below. Can you give an idea of my problem to find the solution?


“Advertencia      2             This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\EntityFramework.6.4.4\build\EntityFramework.props.               C:\Users\xxxxx\Desktop\dentned-master\dentned-master\DentneDModel\DentneDModel.csproj     241        5             DentneDModel”

Atentamente.
España

**Comment by davidegironi** [comment]
There are some nuget packages missing.
You have to compile it using VS. Usually VS install for you the packages missing. If not you should run the Update-Package command, like so: https://learn.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages

**Comment by luism566** [comment]
Thanks for your knowledge and help. I have manually loaded the Nuget in VS2019 manually and I already have a compiled version.

NuGet\Install-Package DG.AdvancedDataGridView -Version 1.2.27314.8

Now I try to create the connection string to the data base in the DentneD.exe.config file in this way but it does not connect see what my mistake is... 
<connectionStrings>
     
> connectionStrings (database connection string) 
     <add name="dentnedEntities" connectionString="Data Source = localhost; Initial Catalog = dentned; ID= sa; Password= 4593" providerName="System.Data.EntityClient" 

I have also tried with this second option and I don't connect...

`< 
    <add name="dentnedEntities" connectionString="Data Source=MSI-GS73\SQLEXPRESS; Initial Catalog=dentned;Integrated Security=false;User ID=sa;Password=4593" providerName="System.Data.EntityClient" />
  </connectionStrings>" `

>Error: Keyword not supported: 'data source'.

Can you give me a reference of the error or solution

Should the database contain values so that there are no NULL errors or empty values? In which tables should I insert values for the application to work?


Thank you ..thank you very much

**Comment by luism566** [comment]
Hello Davide,

I love this app as it provides great flexibility when creating new custom fields in the app. Great job

I have translated the file “en.json” into Spanish and I have called it “es.json”, I configure the output file “DentneD.exe.config” as “es”


     <add key="language" value="en"/>

But the Italian is kept in English if it works

I must be doing something wrong, what is the process to change the language, the translated file was placed in the “Lang” folder but it is still in English.

Once I have tested it, I will attach the translation files for the fact that I am a very kind person and contribute a minimum … minimum detail to your great project.

Sincerely
Luis (Spain)

**Comment by luism566** [comment]
It is already solved , there was a lack of commas in some lines of the language file . fixed

Thank you

**Comment by davidegironi** [comment]
Well done!

**Comment by muhamadnasih** [comment]
> Thank you Davide! I make a query and I hope not to bother you more, I apologize for the inconvenience and thank you for your help. I try to compile the project in visual studio after installing the Microsoft Windows with .NET framework 4.6.2 development module and I am not an expert at all and I get the error that I attach in the image below. Can you give an idea of my problem to find the solution? “Advertencia 2 This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\EntityFramework.6.4.4\build\EntityFramework.props. C:\Users\xxxxx\Desktop\dentned-master\dentned-master\DentneDModel\DentneDModel.csproj 241 5 DentneDModel” Atentamente. España

hi i found out inside the vs compiler got a lot of config file..so which file we need to add the connection string

**Comment by dewtodone** [comment]
I am facing in conneciton string at initial stage where to connect the SQL server db

<add name="dentnedEntities" connectionString="Data Source=mis1;Initial Catalog=dentned;Persist Security Info=True;User ID=sa;password=WeS@dJ$Bxh~Xs; Connect Timeout=100000;" providerName="System.Data.SqlClient"/>

Pls help to resolve the issue

**Comment by Aqeelghaffar93** [comment]
i want help. someone can guide me how to install the software or connect the SQL database

**Comment by lokenangom** [comment]
Hi,

After changing the database path also it shows Database connection error Please help me out
